// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $ao_vivo from "./routes/ao-vivo.tsx";
import * as $api_admin_atualizar from "./routes/api/admin/atualizar.ts";
import * as $api_admin_seed from "./routes/api/admin/seed.ts";
import * as $api_admin_sync_atletas from "./routes/api/admin/sync-atletas.ts";
import * as $api_admin_sync_fotos_apifootball from "./routes/api/admin/sync-fotos-apifootball.ts";
import * as $api_admin_sync_fotos from "./routes/api/admin/sync-fotos.ts";
import * as $api_admin_sync_historico from "./routes/api/admin/sync-historico.ts";
import * as $api_atletas_buscar from "./routes/api/atletas/buscar.ts";
import * as $api_classificacao from "./routes/api/classificacao.ts";
import * as $api_elenco_dono_escalacao from "./routes/api/elenco/[dono]/escalacao.ts";
import * as $api_elenco_dono_index from "./routes/api/elenco/[dono]/index.ts";
import * as $api_elenco_dono_jogador_add from "./routes/api/elenco/[dono]/jogador/add.ts";
import * as $api_elenco_dono_jogador_remove from "./routes/api/elenco/[dono]/jogador/remove.ts";
import * as $api_elenco_dono_jogador_swap from "./routes/api/elenco/[dono]/jogador/swap.ts";
import * as $api_live_path_ from "./routes/api/live/[...path].ts";
import * as $api_ranking from "./routes/api/ranking.ts";
import * as $api_status from "./routes/api/status.ts";
import * as $index from "./routes/index.tsx";
import * as $liga from "./routes/liga.tsx";
import * as $ranking from "./routes/ranking.tsx";
import * as $time_chave_ from "./routes/time/[chave].tsx";
import * as $AoVivoLive from "./islands/AoVivoLive.tsx";
import * as $CollapsibleTeamRow from "./islands/CollapsibleTeamRow.tsx";
import * as $LeagueChart from "./islands/LeagueChart.tsx";
import * as $Ranking from "./islands/Ranking.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/ao-vivo.tsx": $ao_vivo,
    "./routes/api/admin/atualizar.ts": $api_admin_atualizar,
    "./routes/api/admin/seed.ts": $api_admin_seed,
    "./routes/api/admin/sync-atletas.ts": $api_admin_sync_atletas,
    "./routes/api/admin/sync-fotos-apifootball.ts":
      $api_admin_sync_fotos_apifootball,
    "./routes/api/admin/sync-fotos.ts": $api_admin_sync_fotos,
    "./routes/api/admin/sync-historico.ts": $api_admin_sync_historico,
    "./routes/api/atletas/buscar.ts": $api_atletas_buscar,
    "./routes/api/classificacao.ts": $api_classificacao,
    "./routes/api/elenco/[dono]/escalacao.ts": $api_elenco_dono_escalacao,
    "./routes/api/elenco/[dono]/index.ts": $api_elenco_dono_index,
    "./routes/api/elenco/[dono]/jogador/add.ts": $api_elenco_dono_jogador_add,
    "./routes/api/elenco/[dono]/jogador/remove.ts":
      $api_elenco_dono_jogador_remove,
    "./routes/api/elenco/[dono]/jogador/swap.ts": $api_elenco_dono_jogador_swap,
    "./routes/api/live/[...path].ts": $api_live_path_,
    "./routes/api/ranking.ts": $api_ranking,
    "./routes/api/status.ts": $api_status,
    "./routes/index.tsx": $index,
    "./routes/liga.tsx": $liga,
    "./routes/ranking.tsx": $ranking,
    "./routes/time/[chave].tsx": $time_chave_,
  },
  islands: {
    "./islands/AoVivoLive.tsx": $AoVivoLive,
    "./islands/CollapsibleTeamRow.tsx": $CollapsibleTeamRow,
    "./islands/LeagueChart.tsx": $LeagueChart,
    "./islands/Ranking.tsx": $Ranking,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
